language: node_js
node_js:
  - '8'
script:
  - npm run build && npm run test  # jest test with coverage flag does coverage too
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
